### ISSUE TITLE
When removing a User, previous stand-ups break. 

### ISSUE THREAD

**Issue by JasonMannon** [sofetch/slack-standup-bot#22]
When removing a User via command-line, old stand-ups that include that user break.  Maybe adding a flag that excludes a User from the standup rotation, but keeps the user in the DB would be a good solution.

**Comment by santiagodoldan** [comment]
@JasonMannon why not just removing the association and not the user from the db?

**Comment by JasonMannon** [comment]
@santiagodoldan That is a easier solution.
