### ISSUE TITLE
Issues setting up

### ISSUE THREAD

**Issue by brupm** [sofetch/slack-standup-bot#23]
I must be doing something wrong, while filling out /settings.

![screenshot 2015-12-07 11 52 18](https://cloud.githubusercontent.com/assets/336/11638032/8b2f8a80-9cd9-11e5-91ec-f22691ba95f2.png)

I imagine group name is whatever companyname is in companyname.slack.com, bot name is pretty self explanatory, but is what web url? I tried the full url companyname.slack.com and get this:

![screenshot 2015-12-07 11 54 52](https://cloud.githubusercontent.com/assets/336/11638038/91720332-9cd9-11e5-9d18-42d369cd0e29.png)

What should those values be filled with?

**Comment by JasonMannon** [comment]
@brupm

* Group name is the name of your slack private channel.  Private channels used to be called groups, now they are just private channels and that form has not beed updated since then.  So if you have a private channel named "daily-standups" that would be your group name.  

* Web url is your domain for your standup app. For example: http://my-standup-app.herokuapp.com

**Comment by brupm** [comment]
@JasonMannon thanks for the reply, still get the RecordNotFound above after making adjustments.

**Comment by santiagodoldan** [comment]
@brupm what's the output of Channel.all.map(&:attributes) and Setting.all.map(&:attributes)? seems that the channel is not being created correctly

**Comment by brupm** [comment]
```
irb(main):008:0> Channel.all.map(&:attributes)
D, [2015-12-07T17:28:36.096805 #10205] DEBUG -- :   Channel Load (0.4ms)  SELECT `channels`.* FROM `channels`
=> [{"id"=>1, "name"=>"techscrum", "slack_id"=>"G0***VBQ"}]
irb(main):009:0> Setting.all.map(&:attributes)
D, [2015-12-07T17:28:37.672158 #10205] DEBUG -- :   Setting Load (0.4ms)  SELECT `settings`.* FROM `settings`
=> [{"id"=>1, "channel_type"=>"group", "name"=>"techscrum", "bot_id"=>"U0****RDK", "bot_name"=>"techscrum-bot", "web_url"=>""}]
```

Thanks for the help @santiagodoldan

**Comment by santiagodoldan** [comment]
mmmm, that's weird because you already have a channel there and the name is the correct one, not sure how but looks like the associated slack_id is not the same as the one associated to the message, you can try removing that channel and then start another standup, that will create a new one for you.

let us know how it goes doing that.

**Comment by santiagodoldan** [comment]
@brupm is the bot working now?

**Comment by brupm** [comment]
Could not get it to work, mostly given up at this point. If there's manual configuration that should be done in once deployed to heroku, it should likely be documented no?

**Comment by santiagodoldan** [comment]
hey @brupm I'm gonna set up a clean standupbot instance today in heroku, I'll let you know if I have the same problem as you, I'll also share the steps with you.

**Comment by brupm** [comment]
@santiagodoldan sweet! pls let me know how it goes.

**Comment by santiagodoldan** [comment]
@brupm I was able to install the app from scratch, I found some missing steps from the README, so my plan is to improve that, but that won't help you with your problem.

I would recommend you to access the rails console in heroku and then remove all the channels, standups and users (e.g. Channel.delete_all and so on). After removing all those records you can visit your-app.herokuapp.com/api/start and that will create everything again, I hope that fixes the wrong identifier problem you're having.

please, let me know if that works for you.

Cheers

**Comment by santiagodoldan** [comment]
@brupm here you have the updated readme -> #26 

I would recommend you to start everything from scratch (clone the repo again, create a new heroku app, create a new slack private channel, etc) and follow the new steps.

let me know if that works for you.

Cheers

**Comment by brupm** [comment]
Ok, got it to work. Starting fresh did it. thank you.

On Mon, Jan 4, 2016 at 4:36 PM, Santiago Doldán <notifications@github.com>
wrote:

> @brupm <https://github.com/brupm> here you have the updated readme -> #26
> <https://github.com/sofetch/slack-standup-bot/pull/26>
>
> I would recommend you to start everything from scratch (clone the repo
> again, create a new heroku app, create a new slack private channel, etc)
> and follow the new steps.
>
> let me know if that works for you.
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sofetch/slack-standup-bot/issues/23#issuecomment-168854464>
> .
>



-- 
- Bruno

**Comment by santiagodoldan** [comment]
great news :D
