### ISSUE TITLE
can only be used in one Slack channel at a time

### ISSUE THREAD

**Issue by mary-grace** [sofetch/slack-standup-bot#24]
I'm in the process of installing this for my engineering team to use, but don't see a way to use it in multiple Slack channels at once.

I see two options:
- deploy multiple Heroku apps and have different settings for each one
- reset the settings in my app before and after each standup
but neither of these are sustainable or scalable.

When I tried to include multiple channels in the settings, separating them with a comma, it broke the entire app, and I couldn't find a way to fix it. After asking several developer & ops friends for their help, I simply deleted the app and started over.

**Comment by JasonMannon** [comment]
Hey Mary, currently we only use standup-bot on one channel with our Heroku app.  If you need your team to use standup-bot in separate channels, I think deploying multiple Heroku apps would work the best at the moment, or have your team do standups in the same channel. 

Supporting multiple channels at once would be a great feature for us to add in the future, and i'll be sure to update you when we add that functionality.  In the mean time, feel free to leave a pull-request.

**Comment by santiagodoldan** [comment]
Going to close this issue because we didn't implement that yet.

**Comment by santiagodoldan** [comment]
I'm working on this feature, will let you know as soon as I merge this into master

**Comment by santiagodoldan** [comment]
@mary-grace there is a PR that will allow the usage of multiple slack channels, it would be great if you pull that PR and test the functionality. here you have the link #52

**Comment by santiagodoldan** [comment]
this is possible now
