### ISSUE TITLE
is only available for private channels _or_ public channels, not both

### ISSUE THREAD

**Issue by mary-grace** [sofetch/slack-standup-bot#25]
Due to Slack changing their channel names, the app is only available for use in private channels according to your current documentation. I changed
<pre><code>group   = client.channels.detect</code></pre>
in 
<pre><code>app/api/fetch_bot/start.rb</code></pre>
which now allows it to be used only in public channels, not private channels. Is there a way to allow it to be used in both?

**Comment by JasonMannon** [comment]
In this issue: https://github.com/sofetch/slack-standup-bot/issues/24. I mentioned that standup-bot currently only supports one channel per app.  When multi-channel support is added, users should be able to choose between public and private channels when setting up standup-bot.

**Comment by santiagodoldan** [comment]
@mary-grace could you create a PR with that change? that would be great, thanks

**Comment by santiagodoldan** [comment]
@mary-grace here you have the PR that will add support for both private and public channels #29

**Comment by santiagodoldan** [comment]
this is supported now
