### ISSUE TITLE
Emoticons used in slack are not visible on the recap page (nice to have?)

### ISSUE THREAD

**Issue by JordyLangen** [sofetch/slack-standup-bot#31]
Stuff like :simple_smile: is not being converted into an emoticon on the recap page.
It would be nice to have this

**Comment by santiagodoldan** [comment]
yep, that would be awesome, it would be great if you can create a PR for that, here you have a gem that does what you are asking for -> https://github.com/github/gemoji

**Comment by santiagodoldan** [comment]
@JordyLangen there is a PR for this #41

**Comment by santiagodoldan** [comment]
this is already on master, pull latest changes to see emoji images in the report page @JordyLangen

**Comment by JordyLangen** [comment]
Awesome!
