### ISSUE TITLE
Can't start Standup

### ISSUE THREAD

**Issue by jbrodley** [sofetch/slack-standup-bot#59]
I can't get the standup to start by typing /standup. I can see the request hit the server on Heroku. But it the bot never messages to start.

If i take the exact same URL string from the log and paste into a web browser to the herokup app it works just fine.  Any ideas why this may be happening? 

Slack / Command 
Feb 04 04:49:23 mobstandup heroku/router: at=info method=GET path="/api/standups/start?format=text&token=REMOVED&team_id=T02MGJ672&team_domain=mobsupport&channel_id=C03NL8Q46&channel_name=wells&user_id=U02QX6RPC&user_name=jbrodley&command=%2Fstandup&text=&response_url=https%3A%2F%2Fhooks.slack.com%2Fcommands%2FT02MGJ672%2F20312888963%2Fu3RHvBtXoo4zhk5fD4KtrKyG" host=mobstandup.herokuapp.com request_id=6b9affe3-6981-4a99-b9a2-94e03341599f fwd="52.90.146.42" dyno=web.1 connect=12ms service=5ms status=401 bytes=243 

Manually pasted URL to the Heroku App
Feb 04 04:50:18 mobstandup heroku/router: at=info method=GET path="/api/standups/start?format=text&token=REMOVED&team_id=T02MGJ672&team_domain=mobsupport&channel_id=C03NL8Q46&channel_name=wells&user_id=U02QX6RPC&user_name=jbrodley&command=%2Fstandup&text=&response_url=https%3A%2F%2Fhooks.slack.com%2Fcommands%2FT02MGJ672%2F20312888963%2Fu3RHvBtXoo4zhk5fD4KtrKyG" host=mobstandup.herokuapp.com request_id=f3d852f7-bfec-4716-bc4d-f0e4ffa8e7ae fwd="121.244.85.4" dyno=web.1 connect=1ms service=1398ms status=200 bytes=508

**Comment by santiagodoldan** [comment]
Yeah, this was something I added a few weeks ago. When I added password authentication I forgot to not do that within the /api namespace. I need to restrict the password authentication to make the slash command work again. If you have some free time it would be great if you can do that and create a Pull Request.

Cheers

**Comment by nandorocker** [comment]
Same problem here; standup starts fine if I do it via browser URL but can't invoke via /standup

**Comment by dhoffmann** [comment]
#61

**Comment by santiagodoldan** [comment]
thanks @dhoffmann, will review that PR asap

**Comment by santiagodoldan** [comment]
Sorry for the delay guys.

Thanks @dhoffmann for the PR :)
