### ISSUE TITLE
Unable to start a new standup after an incomplete one

### ISSUE THREAD

**Issue by HocineT** [sofetch/slack-standup-bot#68]
Hello, First of all thanks for this project it's great. 
I'm encountering an issue. We didn't complete a standup (someone doesn't answer) during a full day. 

Now I'm trying to start a new standup for the current day but nothing seems to happen. 

Any idea ? 

Thanks !

**Comment by santiagodoldan** [comment]
Hey, the state of that channel didn't change back to "idle", you just need to go to the rails console and change that manually

```ruby
  Channel.find(the_id).stop!
```

Cheers

**Comment by HocineT** [comment]
Thanks a lot @santiagodoldan 

:+1:
