### ISSUE TITLE
Failure to start

### ISSUE THREAD

**Issue by tonyatoms** [sofetch/slack-standup-bot#69]
Greetings,
I'm having trouble getting a new install working. I've configured the slack side of things, and have the Heroku app running, but the /standup command returns: 

> There is no Bot called [correct bot name] within given Channel

It seems the app does not know about the channel. In the heroku irb I'm seeing this:
`irb(main):002:0> Channel.all.map(&:attributes)
  Channel Load (6.5ms)  SELECT "channels".* FROM "channels"
=> []`

`irb(main):003:0> User.all.map(&:attributes)
  User Load (8.7ms)  SELECT "users".* FROM "users"
=> []`

If i try to start from the web I get either the same "There is no bot..." message if I provide a channel name as a parameter (as shown in the local instructions), or the  "There is no bot..." message and "We didn't find the channel you entered, please double check that the name is correct" when I try start the app via this URL: https://APP_NAME.herokuapp.com/api/start

Manually adding a channel (via heroku_pg) does not help. (Although I'm not sure which value is correct for the "slack_id" field.)
thanks!

**Comment by santiagodoldan** [comment]
Did you invite the bot into that channel? /invite @the_name_of_your_bot

**Comment by tonyatoms** [comment]
yes - thanks the bot is listed as a member of the channel. I invited it again, just to be sure.

**Comment by santiagodoldan** [comment]
Double check that your bot's name is the same as the one you have in your settings.

https://github.com/sofetch/slack-standup-bot/blob/master/lib/standupbot/sync.rb#L74

**Comment by tonyatoms** [comment]
uh, can I buy you a beer or something somehow? turns out I had a leading space in front of the bot name in the settings... how embarrassing! thanks for taking your valuable time to help me diagnose such an extreme case of data entry incompetence!

**Comment by santiagodoldan** [comment]
hahaha, no problem :)
