### ISSUE TITLE
Hosting on AWS

### ISSUE THREAD

**Issue by tbookless** [sofetch/slack-standup-bot#71]
Hi, 

Your readme gives detailed instructions for hosting on Heroku. Do you have the same thing for hosting on AWS? Thanks.

Tod

**Comment by santiagodoldan** [comment]
No, we didn't install the bot in AWS yet.

It would be a good idea to have those steps, if you can create a PR it would be great, I'll try to research a bit in my free time too.

Cheers

**Comment by tbookless** [comment]
I have managed to get the bot to install on AWS Elastic Beanstalk, and I set up a Postgres DB for it, but the app throws an error "Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"? The AWS Postgress install has a static, uneditable parameter for "unix_socket_directories" set to "/tmp"

I tried setting up a symbolic link to /tmp but it still failed. So is your app hard coded to require "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by santiagodoldan** [comment]
It looks like you need to define the host where that PG server is running, you can change that in the database.yml file.

https://github.com/sofetch/slack-standup-bot/blob/master/config/database.yml#L40

Lemme know if that fixes your issue.

Cheers

**Comment by tbookless** [comment]
I can now connect to the database, but I get this failure

  + su -s /bin/bash -c 'bundle exec /opt/elasticbeanstalk/support/scripts/check-for-rake-task.rb db:migrate' webapp
  I, [2016-04-19T16:25:14.165113 #5251]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
  + '[' false = true ']'
  + su -s /bin/bash -c 'leader_only bundle exec rake db:migrate' webapp
  I, [2016-04-19T16:25:35.297940 #5340]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
  rake aborted!
  ActiveRecord::NoDatabaseError: FATAL:  database "fetch_bot_production" does not exist

  PG::ConnectionBad: FATAL:  database "fetch_bot_production" does not exist

  Tasks: TOP => db:migrate


--
Tod Bookless
tbookless@tomitribe.com
https://twitter.com/tod_bookless <https://twitter.com/tod_bookless>
http://www.tomitribe.com

**Comment by santiagodoldan** [comment]
You need to create that database "fetch_bot_production", use rake db:create task

Cheers

**Comment by tbookless** [comment]
I don’t have any idea how to do that and I don’t see it in the docs. Do you have any instructions?

**Comment by santiagodoldan** [comment]
I don't have any experience deploying apps to AWS, if you already have a database, could you rename that one to fetch_bot_production? That would be enough, you just need a database with that name.

**Comment by tbookless** [comment]
Tod Bookless has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=188775109388-t33r6vb45j8fgf8vpcp4q0e6qt2pe01n.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.gdocs.win%2Fg.php&customparam=customparam>
